FROM alpine:3.19

RUN apk add --no-cache tigervnc novnc openrc xfce4 xfce4-terminal
COPY --chmod=0755 startapp.sh config.sh ./

RUN ./config.sh

ENTRYPOINT [ "./startapp.sh" ]
CMD ["/bin/sh"]
# CMD xfce4-terminal -e 'sh -c "ls /usr/bin && read"' -T "Run and ready" --zoom=2  --maximize --fullscreen --hide-menubar --hide-borders  --hide-toolbar
