version: '3.9'

services:
  auth-db:
    image: postgres:15
  
  auth:
    image: auth
    build: ./src/Auth/
    depends_on:
      - auth-db
  
  client:
    image: client
    build: ./src/client/

  y-websocket:
    image: y-websocket
    build: ./src/y-websocket/
    
  