version: '3.9'

services:
  auth-db:
    environment:
      - POSTGRES_PASSWORD=password
    # ports:
    #   - "5432:5432"
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        window: 15m

  auth:
    environment:
      - ConnectionStrings:DefaultConnection=Host=auth-db;Port=5432;Database=auth;Username=postgres;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
      - "7099:443"
      
  client:
    ports:
      - "3000:3000"
      
  y-websocket:
    # environment:
    #   - CALLBACK_URL=http://localhost:8123/
    #   - CALLBACK_OBJECTS={"monaco":"Text"}
    ports:
      - "1234:1234"